### ISSUE TITLE
Taro3.6.24模板项目创建后运行测试报错

### ISSUE THREAD

**Issue by tangbzai** [NervJS/taro-test-utils#38]
### 问题描述：
taro 3.6.24版本的模板项目运行测试会报找不到`history`的错误。
- 3.6.23开始有这个问题，回退到3.6.22可以解决该问题
### 错误信息：
```
 FAIL  __tests__/index.test.js
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'history')

    > 1 | import TestUtils from '@tarojs/test-utils-react'
        | ^
      2 |
      3 | describe('Testing', () => {
      4 |

      at Object.history (node_modules/.pnpm/@tarojs+router@3.6.24_@tarojs+runtime@3.6.24_@tarojs+taro@3.6.24/node_modules/@tarojs/router/dist/index.js:47:21)
      at Object.<anonymous> (node_modules/.pnpm/@tarojs+taro-h5@3.6.24_@tarojs+components@3.6.24_@tarojs+taro@3.6.24/node_modules/@tarojs/taro-h5/src/api/taro.ts:37:3)        
      at Object.<anonymous> (node_modules/.pnpm/@tarojs+taro-h5@3.6.24_@tarojs+components@3.6.24_@tarojs+taro@3.6.24/node_modules/@tarojs/taro-h5/dist/index.js:2815:37)       
      at Object.<anonymous> (node_modules/.pnpm/@tarojs+test-utils-react@0.1.1_@babel+core@7.24.0_@tarojs+components@3.6.24_@tarojs+helper@3._gd4weot4ybe46ivih6r3y7qjiq/node_modules/@tarojs/test-utils-react/dist/jest/runtime/taro-h5.js:1:1)
      at Object.<anonymous> (node_modules/.pnpm/@tarojs+components@3.6.24_@tarojs+helper@3.6.24_@tarojs+runtime@3.6.24_@tarojs+shared@3.6.24__fvjn2myy6sdebjsqurs77ec2si/node_modules/@tarojs/components/dist/components/helper.js:1:1)
      at Object.<anonymous> (node_modules/.pnpm/@tarojs+components@3.6.24_@tarojs+helper@3.6.24_@tarojs+runtime@3.6.24_@tarojs+shared@3.6.24__fvjn2myy6sdebjsqurs77ec2si/node_modules/@tarojs/components/dist/components/taro-ad-core.js:2:1)
      at Object.<anonymous> (node_modules/.pnpm/@tarojs+components@3.6.24_@tarojs+helper@3.6.24_@tarojs+runtime@3.6.24_@tarojs+shared@3.6.24__fvjn2myy6sdebjsqurs77ec2si/node_modules/@tarojs/components/dist/components/index.js:2:1)
      at Object.<anonymous> (node_modules/.pnpm/@tarojs+router@3.6.24_@tarojs+runtime@3.6.24_@tarojs+taro@3.6.24/node_modules/@tarojs/router/dist/tabbar.js:1:1)
      at Object.<anonymous> (node_modules/.pnpm/@tarojs+router@3.6.24_@tarojs+runtime@3.6.24_@tarojs+taro@3.6.24/node_modules/@tarojs/router/dist/index.js:2:1)
      at Object.<anonymous> (node_modules/.pnpm/@tarojs+test-utils-react@0.1.1_@babel+core@7.24.0_@tarojs+components@3.6.24_@tarojs+helper@3._gd4weot4ybe46ivih6r3y7qjiq/node_modules/@tarojs/test-utils-react/dist/index.js:41:18)
      at Object.<anonymous> (__tests__/index.test.js:1:1)
      at tryCatch (node_modules/.pnpm/@babel+runtime@7.24.0/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
      at Generator._invoke (node_modules/.pnpm/@babel+runtime@7.24.0/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
      at Generator.next (node_modules/.pnpm/@babel+runtime@7.24.0/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
      at asyncGeneratorStep (node_modules/.pnpm/@babel+runtime@7.24.0/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/.pnpm/@babel+runtime@7.24.0/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        15.156 s
Ran all test suites.
 ELIFECYCLE  Test failed. See above for more details.
```
### 复现步骤：
1. 使用`@tarojs/cli`创建模板项目 (react+pnpm+ts+less+github+默认模板)
2. 项目创建完成并安装完成依赖后运行`pnpm test`

**Comment by jxgzzztang** [comment]
有解决方案吗？

**Comment by tangbzai** [comment]
> 有解决方案吗？

目前没有很好的解决方案，只能回退Taro版本到3.6.22或者不使用这个库。

**Comment by tangbzai** [comment]
我目前定位到问题是出在 [Taro的 #15094 pr](https://github.com/NervJS/taro/pull/15094) 导致的报错。

这个合并里修改了`@tarojs/router` 的 `createRouter` 函数（在函数前面增加了一个`history`参数）而这个库的代码未做对应修改导致的问题。
**具体代码片段：**[packages/taro-router/src/router/spa.ts](https://github.com/NervJS/taro/commit/bbc694db87a67c4a0b5646d94f092946a3533059#diff-e9ad5aaf84147a2101afbacf1bee26039bf387e5f0dba63e057c78715b008a08)
**这个库需要调整的位置：**
- [packages/test-utils-vue/src/index.ts](https://github.com/NervJS/taro-test-utils/blob/7d59a5a80995341dd9eac6c096cd150b27460272/packages/test-utils-vue/src/index.ts#L120)
- [packages/test-utils-react/src/index.ts](https://github.com/NervJS/taro-test-utils/blob/7d59a5a80995341dd9eac6c096cd150b27460272/packages/test-utils-react/src/index.ts#L96)
- [packages/test-utils-vue3/src/index.ts](https://github.com/NervJS/taro-test-utils/blob/7d59a5a80995341dd9eac6c096cd150b27460272/packages/test-utils-vue3/src/index.ts#L107)

@heiazu 麻烦大佬看看如何修改

**Comment by jxgzzztang** [comment]
> > 有解决方案吗？
> 
> 目前没有很好的解决方案，只能回退Taro版本到3.6.22或者不使用这个库。

那只能暂时回退版本了

**Comment by kunkuntang** [comment]
还没解决吗。。。

**Comment by QuentinHsu** [comment]
Amazing！

都 `"@tarojs/taro": "3.6.34"` 了，还没能解决这个问题 😭

**Comment by wangzhengbo** [comment]
这个库都没见维护了

**Comment by bluescurry** [comment]
> 我目前定位到问题是出在 [Taro的 #15094 pr](https://github.com/NervJS/taro/pull/15094) 导致的报错。
> 
> 这个合并里修改了`@tarojs/router` 的 `createRouter` 函数（在函数前面增加了一个`history`参数）而这个库的代码未做对应修改导致的问题。 **具体代码片段：**[packages/taro-router/src/router/spa.ts](https://github.com/NervJS/taro/commit/bbc694db87a67c4a0b5646d94f092946a3533059#diff-e9ad5aaf84147a2101afbacf1bee26039bf387e5f0dba63e057c78715b008a08) **这个库需要调整的位置：**
> 
> * [packages/test-utils-vue/src/index.ts](https://github.com/NervJS/taro-test-utils/blob/7d59a5a80995341dd9eac6c096cd150b27460272/packages/test-utils-vue/src/index.ts#L120)
> * [packages/test-utils-react/src/index.ts](https://github.com/NervJS/taro-test-utils/blob/7d59a5a80995341dd9eac6c096cd150b27460272/packages/test-utils-react/src/index.ts#L96)
> * [packages/test-utils-vue3/src/index.ts](https://github.com/NervJS/taro-test-utils/blob/7d59a5a80995341dd9eac6c096cd150b27460272/packages/test-utils-vue3/src/index.ts#L107)
> 
> @heiazu 麻烦大佬看看如何修改

你有尝试修改源码解决吗，我 fork 下来加上了这几行代码，但还是报错
```tsx
Current.page = {
      path: '/pages/index/index'
    }
    document.body.innerHTML = `<div id="app"><div id="${Current.page.path}" class="taro_page" /></div>`

    // @ts-ignore
   // 下面这三行是修改后的代码
    const history = createHashHistory({ window })
    handleAppMountWithTabbar(config, history)
    createRouter(history, appInst, config, 'React')

    await waitRAF()

    return {
      app: appInst,
      page: Current.page
    }
```

**Comment by liaozhangpeng** [comment]
same issue

**Comment by y-not-u** [comment]
You guys don't need unit test for projects? Are you kidding me?
